name: Swift

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 13' -scheme 'DHDeclarable'
    - name: Gather code coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/DHDeclarablePackageTests.xctest/Contents/MacOS/DHDeclarablePackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage_report.lcov
        verbose: true
