name: dev workflow

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 13' -scheme 'DHDeclarable' -enableCodeCoverage YES
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
