name: run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 13' -scheme 'DHDeclarable' -enableCodeCoverage YES
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'DHDeclarable'
    - name: discord notification
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
